workspace:
  base: /go
  path: src/drone-golang-example

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: golang
    commands:
      - make fmt-check
      - make test
